name: rcp2
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster
  - applaunchservices
  - argh
  - astroid
  - atomicwrites
  - attrs
  - autopep8
  - babel
  - backcall
  - bleach
  - boost-cpp
  - brotlipy
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - chardet
  - chart-studio
  - click
  - click-plugins
  - cligj
  - cloudpickle
  - colorlover
  - cryptography
  - cufflinks-py
  - curl
  - cycler
  - dbus
  - decorator
  - defusedxml
  - diff-match-patch
  - docutils
  - entrypoints
  - expat
  - fiona
  - flake8
  - fontconfig
  - freetype
  - freexl
  - future
  - gdal
  - geopandas
  - geos
  - geotiff
  - gettext
  - giflib
  - glib
  - hdf4
  - hdf5
  - icu
  - idna
  - imagesize
  - imbalanced-learn
  - importlib-metadata
  - importlib_metadata
  - intervaltree
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json-c
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - kealib
  - keyring
  - kiwisolver
  - krb5
  - lazy-object-proxy
  - libblas
  - libcblas
  - libclang
  - libcurl
  - libcxx
  - libdap4
  - libedit
  - libffi
  - libgdal
  - libgfortran
  - libiconv
  - libkml
  - liblapack
  - libllvm9
  - libnetcdf
  - libopenblas
  - libpng
  - libpq
  - libsodium
  - libspatialindex
  - libspatialite
  - libssh2
  - libtiff
  - libwebp-base
  - libxml2
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mccabe
  - missingno
  - mistune
  - munch
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - nspr
  - nss
  - numpy
  - numpydoc
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pandas-profiling
  - pandoc
  - pandocfilters
  - parso
  - pathtools
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pip
  - pixman
  - plotly
  - pluggy
  - poppler
  - poppler-data
  - postgresql
  - proj
  - prometheus_client
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pycodestyle
  - pycparser
  - pydocstyle
  - pyflakes
  - pygments
  - pylint
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pyrsistent
  - pysocks
  - python
  - python-cufflinks
  - python-dateutil
  - python-jsonrpc-server
  - python-language-server
  - python_abi
  - pytz
  - pyyaml
  - pyzmq
  - qdarkstyle
  - qt
  - qtawesome
  - qtconsole
  - qtpy
  - readline
  - requests
  - retrying
  - rope
  - rtree
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - shapely
  - six
  - snowballstemmer
  - sortedcontainers
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - spyder
  - spyder-kernels
  - sqlite
  - statsmodels
  - tbb
  - terminado
  - testpath
  - threadpoolctl
  - tiledb
  - tk
  - toml
  - tornado
  - traitlets
  - tzcode
  - ujson
  - urllib3
  - watchdog
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - wrapt
  - wurlitzer
  - xerces-c
  - xlrd
  - xz
  - yaml
  - yapf
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - pyqt5-sip
    - pyqtchart
    - pyqtwebengine


